alias binstall="bundle install --path .bundle --jobs=4"
alias bexec="bundle exec"
alias brake="bundle exec rake"
alias bspec="bundle exec rspec"
alias bpry="bundle exec pry"

alias b="bundle"
alias bi="bundle install --path .bundle --jobs=4"
alias bu="bundle update"
alias be="bundle exec"
alias br="bundle exec rspec"
alias bs="bundle exec rspec"
